Added param checks for method parse_search_string().
oalders/uri-parsesearchstring-more pull request #3
Opened 2018-10-14 05:18 UTC by manwar

Hi @oalders 

Please review the PR.
Added basic param validation to the method parse_search_string().

Many Thanks.
Best Regards,
Mohammad S Anwar

2018-10-14 15:13 UTC, oalders requested changes

2018-10-14 15:13 UTC, oalders commented on t/005_parse_more.t
> +like ($@, qr/missing url/);
How about using `Test::Fatal` here?

```perl
use Test::Fatal;

...

like(
  exception { $more->parse_search_string;  },
  qr/missing url/,
  'dies on missing URL',
);

2018-10-14 15:13 UTC, oalders commented
Thanks @manwar! Just added a comment for you to consider.

2018-10-14 16:00 UTC, manwar commented
Done as suggested.
Please review it again.

Best Regards,
Mohammad S Anwar

2018-10-15 00:56 UTC, oalders approved these changes

2018-10-15 00:56 UTC, oalders commented
Wonderful. Thanks @manwar!

2018-10-15 00:56 UTC, merged